mock_mode: true

mqtt:
  broker: "127.0.0.1"
  port: 1883
  topic: "adp/v1/event/S001"
  client_id: "front_vision_env01"

store_id: "S001"
device_id: "SENSOR_ENV01"

report:
  env_report_interval_s: 5

sensor_modbus:
  serial_port: "/dev/ttyUSB0"
  serial_port_backup: "/dev/ttyUSB1"
  baudrate: 9600
  slave_id: 2
